apiVersion: v1
kind: Service
metadata:
  name: dclaw-med
  namespace: dclaw-core
  labels:
    app.kubernetes.io/name: dclaw-med
    app.kubernetes.io/part-of: dclaw-platform
spec:
  type: NodePort
  ports:
    - port: 3004
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30004
  selector:
    app.kubernetes.io/name: dclaw-med
